core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    # incription form
    url(r'^', include('inscription.urls')),

    # ADMIN
    url(r'^admin/', admin.site.urls),
]

if settings.LOCAL:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)

inscription/urls.py
from django.conf.urls import url

from inscription import views

urlpatterns = [

    #####################
    # INSCRIPTION
    #####################

    # /
    url(r'^$', views.Inscription.as_view(), name='form-new'),

    # /success
    url(
        r'^success/(?P<pk>[0-9]+)/$',
        views.InscriptionSuccess.as_view(),
        name='form-success'),


    ############################
    # CURADORIA MOSTRA REGIONAL
    ############################

    # /mostra/regional
    url(
        r'^mostra/regional/$',
        views.InscriptionMostraRegional.as_view(),
        name='mostra-regional'),

    # /mostra/regional/espetaculo-da-mostra-regional
    url(
        r'^mostra/regional/(?P<slug>[\w-]+)$',
        views.InscriptionMostraRegionalEspetaculo.as_view(),
        name='mostra-regional-espetaculo'),
]


############################
# chunked_upload urls
############################

urlpatterns += [

    url(r'^chunked$',
        views.ChunkedUploadDemo.as_view(), name='chunked_upload'),

    url(r'^chunked/api/chunked_upload/?$',
        views.MyChunkedUploadView.as_view(), name='api_chunked_upload'),

    url(r'^chunked/api/chunked_upload_complete/?$',
        views.MyChunkedUploadCompleteView.as_view(),
        name='api_chunked_upload_complete'),
]

inscription/models.py
from __future__ import unicode_literals

import uuid

from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

from chunked_upload.models import ChunkedUpload

from .validators import FileValidator


class InscriptionValidManager(models.Manager):
    ''' Filtro para retornar inscrições válidas '''

    def get_queryset(self):
        return super().get_queryset().filter(
            status=Inscription.VALIDA).order_by('grupo', 'espetaculo')


class Inscription(models.Model):

    def __str__(self):
        return '%s - %s - %s' % (
            self.grupo,
            self.espetaculo,
            self.MOSTRA_OPC[self.mostra - 1][1])

    def get_absolute_url(self):
        kwargs = {'slug': self.slug}
        return reverse('mostra-regional-espetaculo', kwargs=kwargs)

    def get_upload_to_file(self, filename):
        ext = filename[-3:].lower()

        return 'inscription/%s-%s.%s' % (
            uuid.uuid4(),
            slugify(filename.strip()),
            ext)

    def save(self, *args, **kwargs):
        if not self.id:
            super().save(*args, **kwargs)

        if not self.slug:
            self.slug = slugify(self.__str__().strip())

        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Espetáculo inscrito"
        verbose_name_plural = "Espetáculos inscritos"

    REGIONAL = 1
    ESTADUAL = 2
    NACIONAL = 3

    MOSTRA_OPC = (
        (REGIONAL, 'REGIONAL'),
        (ESTADUAL, 'ESTADUAL'),
        (NACIONAL, 'NACIONAL'),
    )

    INVALIDA = 1
    VALIDA = 2
    SELECIONADA = 3

    MOSTRA_STATUS = (
        (INVALIDA, 'Inválida'),
        (VALIDA, 'Válida'),
        (SELECIONADA, 'Selecionada'),
    )

    """ Managers """
    objects = models.Manager()
    valid = InscriptionValidManager()

    """ Fields """
    grupo = models.CharField('Nome do grupo', max_length=200)
    espetaculo = models.CharField('Nome do espetáculo', max_length=200)
    mostra = models.PositiveSmallIntegerField('Mostra', choices=MOSTRA_OPC)
    slug = models.SlugField(max_length=200, null=True, blank=True)
    release = models.TextField('Release')
    sinopse = models.TextField('Sinopse')
    ficha_tecnica = models.TextField('Ficha técnica')
    historico = models.TextField('Histórico da peça/ Grupo')

    pesquisa = models.TextField('Proposta de pesquisa e encenação')

    classificacao = models.CharField('Classificação indicativa', max_length=50)
    duracao = models.CharField('Duração do espetáculo', max_length=50)

    email = models.EmailField(
        'E-mail',
        help_text='Entraremos em contato por este canal')

    email_optional = models.EmailField(
        'E-mail opcional',
        null=True, blank=True)

    contato = models.TextField(
        'Contatos do grupo pra divulgação',
        help_text='Site, blog, e-mail, redes sociais, etc')

    rider_tecnico = models.TextField(
        'Rider Técnico',
        help_text='Especificar necessidades técnicas, mapa de som e luz')

    links = models.TextField(
        'Links de vídeo do espetáculo',
        help_text='Se o link do vídeo for fechado enviar senha. Em caso de espetáculos \
        inéditos, deverão ser encaminhados vídeos de ensaio')

    tempo_des_montagem = models.CharField(
        'Tempo de montagem e desmontagem',
        max_length=100)

    # PDF!!!
    autorizacao = models.FileField(
        'Autorização',
        help_text='Autorização SBAT ou liberação do autor (.PDF)',
        upload_to=get_upload_to_file,
        validators=[FileValidator(
            allowed_mimetypes=(
                'application/pdf',),
            max_size=4 * 1024 * 1024), ],)

    # PDF!!!
    clipping = models.FileField(
        'Clipping, materiais adicionais',
        help_text='Selecione um arquivo PDF',
        upload_to=get_upload_to_file,
        validators=[FileValidator(
            allowed_mimetypes=(
                'application/pdf',),
            max_size=4 * 1024 * 1024), ],)

    status = models.PositiveSmallIntegerField(
        'Situação', choices=MOSTRA_STATUS, default=VALIDA)

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    obs = models.TextField(
        'Observações',
        help_text='Observações internas',
        null=True, blank=True)


class InscriptionImages(models.Model):

    """
    TODO:
        - plugin para versões otimizadas das imagens
    """

    def __str__(self):
        return '%s' % (self.image)

    def get_upload_to_image(self, filename):
        ext = filename[-3:].lower()
        if ext == 'peg':
            ext = 'jpeg'

        return 'inscription/%s/%s-%s.%s' % (
            self.inscription_id,
            uuid.uuid4(),
            slugify(filename.strip()),
            ext)

    class Meta:
        verbose_name = "Fotos da inscrição"
        verbose_name_plural = "Fotos da inscrição"

    inscription = models.ForeignKey(
        Inscription,
        null=True, blank=True,
        verbose_name=u"Inscrição",
        on_delete=models.CASCADE)

    image = models.ImageField(
        'Imagem',
        upload_to=get_upload_to_image,
        max_length=300)

    image_opt = models.ImageField(
        'Imagem Otimizada',
        upload_to=get_upload_to_image,
        max_length=300,
        null=True, blank=True)


class MyChunkedUpload(ChunkedUpload):
    pass


# Override the default ChunkedUpload to make the `user` field nullable
MyChunkedUpload._meta.get_field('user').null = True

inscription/forms.py
from django.forms import ModelForm

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import Inscription


class InscriptionForm(ModelForm):

    class Meta:
        model = Inscription
        exclude = ['slug',]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-exampleForm'
        self.helper.form_class = 'blueForms'
        self.helper.form_method = 'post'

        self.helper.add_input(Submit('submit', 'Próximo passo'))

inscription/views.py
import mimetypes
import re

from django.core.mail import mail_managers, send_mail as sendmail
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic import ListView
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from chunked_upload.views import ChunkedUploadView, ChunkedUploadCompleteView
from chunked_upload.exceptions import ChunkedUploadError
from chunked_upload.constants import http_status

from .models import Inscription as Inscr, MyChunkedUpload, InscriptionImages
from .forms import InscriptionForm


class Inscription(CreateView):

    model = Inscr
    form_class = InscriptionForm
    template_name = 'inscription/form_unavailable.html'
    success_url = reverse_lazy('chunked_upload')

    def send_mail(self):

        post = self.request.POST

        mostra_opc = dict(self.model.MOSTRA_OPC)
        mostra_sel = int(post['mostra'])

        subject = 'Inscrição - %s - %s - %s' % (
            post['grupo'],
            post['espetaculo'],
            mostra_opc[mostra_sel])

        change_url = reverse_lazy('admin:inscription_inscription_change',
                                  args=(self.object.id,))
        url = str(self.request.build_absolute_uri(str(change_url)))

        msg = """
Ficha de inscrição

Grupo: %s
Espetáculo: %s
Mostra: %s

Release: %s

Sinopse: %s

Histórico: %s

Ficha técnica: %s

Proposta de pesquisa: %s

Contato: %s

%s

        """ % (post['grupo'], post['espetaculo'],
               mostra_opc[mostra_sel], post['release'],
               post['sinopse'], post['historico'], post['ficha_tecnica'],
               post['pesquisa'], post['contato'], url)

        try:
            mail_managers(subject, msg, fail_silently=False)
        except Exception as e:
            if settings.DEBUG:
                raise
            return False

        return True

    def send_mail_mostra_regional(self):

        post = self.request.POST

        contact_list = re.compile(",|\s|;").split(post['contato'])
        contact_list = [mail for mail in contact_list if re.match('(\w+@\w+)', mail)]

        subject = 'Inscrição e informações importantes'

        msg = """
Parabéns, sua inscrição foi reaizada com sucesso!!


Art. 5º-  Mostra Regional da Baixada Santista

a )   Seguindo o modelo de curadoria coletiva proposto pelo Movimento Teatral da Baixada Santista, a seleção será realizada em 3 etapas:


ETAPA 1- Atividade formativa voltada à curadoria com participação de pelo menos 1 (hum) integrante do grupo inscrito no dia 23 de junho; domingo às 17h na Cadeia Velha(opção 1) ou no Teatro Guarany (Opção 2) com Alexandre Mate.


ETAPA 2- Atividade formativa voltada à curadoria com participação de pelo menos 1 (hum) integrante do grupo inscrito no dia 30 de junho; domingo às 17h na Cadeia Velha(opção 1) ou no Teatro Guarany (Opção 2) com Kil Abreu.


ETAPA 3 – Integrante que participou das atividades formativas poderá votar pelo grupo que representa em reunião de curadoria da mostra regional no dia 14 de Julho, domingo às 14h, no Centro Cultural Cadeia Velha, após o fim das inscrições, em comissão formada por um integrante de cada grupo inscrito e a organização do festival, não sendo válido avaliar o seu próprio trabalho - sistema de voto aberto e justificado durante a reunião.

        """

        try:
            sendmail(subject, msg, settings.DEFAULT_FROM_EMAIL,
                     contact_list, fail_silently=False)
        except Exception as e:
            if settings.DEBUG:
                raise
            return False

        return True

    def form_valid(self, form):
        self.object = form.save()

        self.send_mail()
        self.object.save()

        if int(self.object.mostra) == self.model.REGIONAL:
            self.send_mail_mostra_regional()

        self.request.session['count_chunk'] = 0
        self.request.session['inscription_id'] = self.object.id

        return super().form_valid(form)


class ChunkedUploadDemo(TemplateView):
    template_name = 'chunked_demo/chunked_upload_demo.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.session.get('inscription_id', False):
            return redirect('form-new')

        return super().dispatch(request, *args, **kwargs)


class MyChunkedUploadView(ChunkedUploadView):

    model = MyChunkedUpload
    field_name = 'the_file'

    mime_message = _("MIME type '%(mimetype)s' is not valid. \
        Allowed types are: %(allowed_mimetypes)s.")
    allowed_mimetypes = (
        'image/png',
        'image/jpeg')

    def check_permissions(self, request):
        # Allow non authenticated users to make uploads
        pass

    def is_valid_chunked_upload(self, chunked_upload):

        mimetype = mimetypes.guess_type(chunked_upload.filename)[0]
        if self.allowed_mimetypes and not mimetype in self.allowed_mimetypes:
            message = self.mime_message % {
                'mimetype': mimetype,
                'allowed_mimetypes': ', '.join(self.allowed_mimetypes)
            }

            raise ChunkedUploadError(status=http_status.HTTP_400_BAD_REQUEST,
                                     detail=message)

        return super().is_valid_chunked_upload(chunked_upload)



class MyChunkedUploadCompleteView(ChunkedUploadCompleteView):

    model = MyChunkedUpload
    do_md5_check = False

    def check_permissions(self, request):
        # Allow non authenticated users to make uploads
        pass

    def on_completion(self, uploaded_file, request):
        # Do something with the uploaded file. E.g.:
        # * Store the uploaded file on another model:
        InscriptionImages.objects.create(
            inscription_id=request.session.get('inscription_id'),
            image=uploaded_file)

        self.request.session['count_chunk'] += 1
        # * Pass it as an argument to a function:
        # function_that_process_file(uploaded_file)

    def get_response_data(self, chunked_upload, request):

        return {'message': ("You successfully uploaded '%s' (%s bytes)!" %
                            (chunked_upload.filename, chunked_upload.offset))}


class InscriptionSuccess(DetailView):
    model = Inscr
    context_object_name = 'obj'
    template_name = 'inscription/form_success.html'

    def send_mail(self):
        obj = self.model.objects.get(id=self.request.session['inscription_id'])
        subject = 'Fotos da inscrição - %s' % obj.__str__()

        change_url = reverse_lazy(
            'admin:inscription_inscription_change',
            args=(self.request.session['inscription_id'],))

        url = str(self.request.build_absolute_uri(str(change_url)))

        msg = """
Fotos da inscrição

%s

        """ % (url, )

        try:
            mail_managers(subject, msg, fail_silently=False)
        except Exception as e:
            if settings.DEBUG:
                raise
            return False

        return True

    def dispatch(self, request, *args, **kwargs):

        if not request.session.get('inscription_id', False):
            return redirect('form-new')

        send = self.send_mail()

        del self.request.session['count_chunk']
        del self.request.session['inscription_id']

        # GARBAGE COLLECTION ON CHUNKED

        return super().dispatch(request, *args, **kwargs)


class InscriptionMostraRegional(ListView):

    template_name = 'inscription/mostra_regional.html'
    context_object_name = 'inscriptions'

    def get_queryset(self):
        return Inscr.valid.filter(mostra=Inscr.REGIONAL)


class InscriptionMostraRegionalEspetaculo(DetailView):

    template_name = 'inscription/mostra_regional_espetaculo.html'
    context_object_name = 'i'

    def get_queryset(self):
        return Inscr.valid.all()

inscription/templates/inscription/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h2>Inscrição</h2>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% crispy form %}

{% endblock content %}

inscription/templates/inscription/form_success.html
{% extends 'base.html' %}

{% block content %}

<h2>Inscrição</h2>

<p>Inscrição realizada com sucesso!</p>

{% endblock content %}

inscription/templates/inscription/form_unavailable.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h2>Inscrição</h2>

<h4>As incrições estão encerradas!</h4>
<p>
	Para maiores informações acesse o 
    <a target="_blank" href="https://movimentoteatraldabaixadasantista.blogspot.com/2019/05/de-chamamento-para-participacao-de.html">
		edital de chamamento.
	</a>
</p>

{% endblock content %}

{% block nav_back %}{% endblock nav_back %}

inscription/templates/inscription/mostra_regional.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Inscrições: Mostra Regional{% endblock %}

{% block content %}
    
    <br><h2>Inscrições: Mostra Regional</h2><br>

    {% for i in inscriptions %}

    <div class="row" class="espetaculo-item">
        <div class="col-md-12">
            <a href="{{ i.get_absolute_url }}"><h4>{{ i.grupo }} - {{ i.espetaculo }}</h4></a>
        </div>
        <div class="col-md-8">
            <p>
                <b>Sinopse:</b><br>
                {{ i.sinopse }}
            </p>
        </div>
        <div class="col-md-4">
            <br>
            <img src="{{ i.inscriptionimages_set.first.image_opt.url }}" width="100%">
        </div>
        <div class="col-md-12">
            <hr>
        </div>
    </div>

    {% endfor %}

{% endblock %}

inscription/templates/inscription/mostra_regional_espetaculo.html
{% extends "base.html" %}

{% block title %}Inscrições: Mostra Regional{% endblock %}

{% block content %}
    <br>
    <h2>{{ i.espetaculo }} <br> ({{ i.grupo }})</h2>
    <br><br>
    <div id="div_id_release" class="form-group">
        <label for="id_release" class="control-label  requiredField">
        Release </label> 
        <div class="controls "> <textarea name="release" readonly="true" cols="40" id="id_release" rows="10" class="textarea form-control">{{ i.release }}</textarea> </div>
    </div>
    <div id="div_id_sinopse" class="form-group">
        <label for="id_sinopse" class="control-label  requiredField">
        Sinopse </label> 
        <div class="controls "> <textarea name="sinopse" readonly="true" cols="40" id="id_sinopse" rows="10" class="textarea form-control">{{ i.sinopse }}</textarea> </div>
    </div>
    <div id="div_id_ficha_tecnica" class="form-group">
        <label for="id_ficha_tecnica" class="control-label  requiredField">
        Ficha técnica </label> 
        <div class="controls "> <textarea name="ficha_tecnica" readonly="true" cols="40" id="id_ficha_tecnica" rows="10" class="textarea form-control">{{ i.ficha_tecnica }}</textarea> </div>
    </div>
    <div id="div_id_historico" class="form-group">
        <label for="id_historico" class="control-label  requiredField">
        Histórico da peça/ Grupo </label> 
        <div class="controls "> <textarea name="historico" readonly="true" cols="40" id="id_historico" rows="10" class="textarea form-control">{{ i.historico }}</textarea> </div>
    </div>
    <div id="div_id_pesquisa" class="form-group">
        <label for="id_pesquisa" class="control-label  requiredField">
        Proposta de pesquisa e encenação </label> 
        <div class="controls "> <textarea name="pesquisa" readonly="true" cols="40" id="id_pesquisa" rows="10" class="textarea form-control">{{ i.pesquisa }}</textarea> </div>
    </div>
    <div id="div_id_classificacao" class="form-group">
        <label for="id_classificacao" class="control-label  requiredField">
        Classificação indicativa </label> 
        <div class="controls "> <input name="classificacao" readonly="true" class="textinput textInput form-control" value="{{ i.classificacao }}" maxlength="50" id="id_classificacao" type="text"> </div>
    </div>
    <div id="div_id_duracao" class="form-group">
        <label for="id_duracao" class="control-label  requiredField">
        Duração do espetáculo </label> 
        <div class="controls "> <input name="duracao" readonly="true" class="textinput textInput form-control" value="{{ i.duracao }}" maxlength="50" id="id_duracao" type="text"> </div>
    </div>
    <div id="div_id_contato" class="form-group">
        <label for="id_contato" class="control-label  requiredField">
        Contato do grupo pra divulgação </label> 
        <div class="controls ">
            <textarea name="contato" readonly="true" cols="40" id="id_contato" rows="10" class="textarea form-control">{{ i.contato }}</textarea>
        </div>
    </div>
    <div id="div_id_rider_tecnico" class="form-group">
        <label for="id_rider_tecnico" class="control-label  requiredField">
        Rider Técnico </label> 
        <div class="controls ">
            <textarea name="rider_tecnico" readonly="true" cols="40" id="id_rider_tecnico" rows="10" class="textarea form-control">{{ i.rider_tecnico }}</textarea>
        </div>
    </div>
    <div id="div_id_links" class="form-group">
        <label for="id_links" class="control-label  requiredField">
        Links de vídeo do espetáculo </label> 
        <div class="controls ">
            <textarea name="links" readonly="true" cols="40" id="id_links" rows="10" class="textarea form-control">{{ i.links }}</textarea>
        </div>
    </div>
    <div id="div_id_tempo_des_montagem" class="form-group">
        <label for="id_tempo_des_montagem" class="control-label  requiredField">
        Tempo de montagem e desmontagem </label> 
        <div class="controls "> <input name="tempo_des_montagem" readonly="true" class="textinput textInput form-control" value="{{ i.tempo_des_montagem }}" maxlength="100" id="id_tempo_des_montagem" type="text"> </div>
    </div>
    <div id="div_id_autorizacao" class="form-group">
        <label for="id_autorizacao" class="control-label  requiredField">
        Autorização </label> 
        <div class="controls ">
            <a href="{{ i.autorizacao.url }}" target="_blank">clique aqui</a>
        </div>
    </div>
    <div id="div_id_clipping" class="form-group">
        <label for="id_clipping" class="control-label  requiredField">
        Clipping, materiais adicionais </label> 
        <div class="controls ">
            <a href="{{ i.clipping.url }}" target="_blank">clique aqui</a>
        </div>
    </div>

    <div class="form-group">
        <label for="id_clipping" class="control-label  requiredField">
        Fotos </label><br><br>

        {% for im in i.inscriptionimages_set.all %}

        <div class="col-md-4">
            <a href="{{ im.image.url }}">
                <img src="{{ im.image_opt.url }}" width="100%">
            </a>
             <br><br>
        </div>

        {% endfor %}
    </div>
{% endblock %}